tourism_clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST', 'clickhouse') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', '') }}"
      schema: default          # clickhouse adapter treats schema as the database
      database: default        # harmless; adapter mostly uses `schema` as DB name
      secure: false
      verify: true
      threads: 4
      cluster_mode: false
