FROM python:3.10-slim

# Set the working directory
WORKDIR /app

COPY . .

# Copy the requirements file and install dependencies
COPY py_requirements.txt .
RUN pip install --no-cache-dir -r py_requirements.txt

# Command to run the application
ENTRYPOINT ["python", "src/ingestion/ingestion.py"]
