FROM apache/airflow:2.8.1

USER root
RUN apt-get update && apt-get install -y build-essential gcc wget && rm -rf /var/lib/apt/lists/*

USER airflow
COPY py_requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt \
    && pip install --no-cache-dir clickhouse-connect==0.7.* dbt-core==1.7.* dbt-clickhouse==1.7.*

ENV PYTHONPATH="/opt/airflow:${PYTHONPATH}"
ENV DBT_PROFILES_DIR=/opt/airflow/dbt
